server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: naxin
  datasource:
      url: jdbc:mysql://localhost:3306/lab_registration
      username: root
      password: your_password
  driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.naxin.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.naxin: DEBUG
